import { useEffect, useState } from "react";
import { MAX_COACH_QUESTION_LENGTH, type CoachSessionFacts } from "@ai-rehab/contracts";
import { ApiError, askCoach, fetchCoachStatus, isApiConfigured } from "../lib/api.js";
import { isSignedIn } from "../lib/authStore.js";
import { Button } from "./Button.js";
import { Icon } from "./Icon.js";

/**
 * C1/C3 — ask about the set you just finished (ADR-0009).
 *
 * Placed on the summary, which is the slow loop: the set is over, nothing is
 * being measured, and ADR-0001's ban on models in the per-frame path is not
 * in play.
 *
 * Two things are deliberately visible rather than tucked away. The answer is
 * labelled as coming from a language model, because a generated sentence
 * should not be indistinguishable from the app's own measurements sitting
 * inches above it. And the fact that the session's figures are sent to Groq
 * is stated here, not only in a privacy screen — the moment someone decides
 * to ask is the moment that matters.
 */

const SUGGESTIONS = [
  "How did that set go?",
  "What should I focus on next time?",
  "Why was my form marked down?"
];

export function CoachPanel({ facts }: { facts: CoachSessionFacts }) {
  const [available, setAvailable] = useState(false);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<{ answer: string; model: string } | null>(null);
  const [asking, setAsking] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!isApiConfigured() || !isSignedIn()) return;
    fetchCoachStatus()
      .then((s) => setAvailable(s.available))
      .catch(() => setAvailable(false));
  }, []);

  // Nothing to offer, so nothing is shown. An "unavailable" panel would be
  // clutter on a screen the patient reads once.
  if (!available) return null;

  async function ask(q: string) {
    const trimmed = q.trim();
    if (!trimmed) return;
    setAsking(true);
    setError(null);
    setAnswer(null);
    try {
      setAnswer(await askCoach({ question: trimmed, facts }));
      setQuestion("");
    } catch (err) {
      setError(
        err instanceof ApiError
          ? err.message
          : "The coach isn't available right now. Your session is saved either way."
      );
    } finally {
      setAsking(false);
    }
  }

  return (
    <div className="ds-card-hair flex flex-col gap-10">
      <span className="ds-label">Ask about this set</span>

      {answer && (
        <div className="flex flex-col gap-6 rounded-md bg-teal-wash p-14">
          <p className="text-b1 text-teal-deep">{answer.answer}</p>
          <span className="font-mono text-lb uppercase text-teal-deep/70">
            Generated by {answer.model}
          </span>
        </div>
      )}

      {error && <p className="text-b2 text-dang">{error}</p>}

      {!answer && (
        <div className="flex flex-wrap gap-6">
          {SUGGESTIONS.map((s) => (
            <button
              key={s}
              type="button"
              disabled={asking}
              onClick={() => ask(s)}
              className="ds-chip bg-sunk text-ink-2 disabled:opacity-50"
            >
              {s}
            </button>
          ))}
        </div>
      )}

      <div className="flex flex-col gap-8">
        <textarea
          value={question}
          onChange={(e) => setQuestion(e.target.value.slice(0, MAX_COACH_QUESTION_LENGTH))}
          rows={2}
          placeholder="Ask your own question…"
          aria-label="Ask the coach a question"
          className="resize-none rounded bg-surf p-12 text-b2 text-ink shadow-hair placeholder:text-ink-3"
        />
        <Button onClick={() => ask(question)} disabled={asking || question.trim().length === 0}>
          {asking ? "Thinking…" : "Ask"}
        </Button>
      </div>

      <p className="flex items-start gap-8 text-[11.5px] leading-[1.4] text-ink-3">
        <Icon name="warning" size={13} className="mt-1" />
        <span>
          This set's figures are sent to Groq, an AI service, to answer you. Your camera video is
          not. Answers are generated and can be wrong — they are not medical advice, and your
          clinician's instructions come first.
        </span>
      </p>
    </div>
  );
}
